version: '3.9'

services:
  node:
    image: vitalii_iakunin/home-library:app
    container_name: app
    build: ./
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app/
      - node-modules:/usr/app/node_modules
    depends_on:
      - db
    networks:
      - net
  
  db:
    image: vitalii_iakunin/home-library:db
    container_name: db
    build: ./db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - data:/db/data
      - logs:/db/logs
    networks:
      - net

volumes:
  node-modules:
  logs:
  data:

networks:
  net:
    driver: bridge
