version: '3.9'

services:
  node:
    container_name: nodejs2023-service
    image: vitalijiakunin/nodejs2023-service
    build: ./
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app/
      - node-modules:/usr/app/node_modules
    depends_on:
      - db
    networks:
      - net
  
  db:
    container_name: nodejs2023-docker-db
    image: vitilijiakunin/nodejs2023-docker-db
    build: ./db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - data:/db/data
      - logs:/db/logs
    networks:
      - net

volumes:
  node-modules:
  logs:
  data:

networks:
  net:
    driver: bridge
